
server.port=${MCH_WEB_PORT:8080}

spring.datasource.url=${MCH_DB_URL:jdbc:h2:file:./data/mch-db}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${MCH_DB_USERNAME:sa}
spring.datasource.password=${MCH_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

mch.discord.token=${DISCORD_TOKEN:}
mch.discord.server-info.guild-name=${MCH_DISCORD_INFO_GUILD:99B Works}
mch.discord.server-info.channel-name=${MCH_DISCORD_INFO_CHANNEL:serverinfo}
mch.minecraft.data-dir=${MCH_DATA_DIR:./data}
mch.minecraft.java-command=${MCH_JAVA_COMMAND:java}
mch.minecraft.memory=${MCH_MEMORY:-Xmx750M}
mch.minecraft.min-port=${MCH_MIN_PORT:25000}
mch.minecraft.max-port=${MCH_MAX_PORT:26000}
mch.minecraft.max-servers=${MCH_MAX_SERVERS:50}
mch.minecraft.auto-update-paper=${MCH_AUTO_UPDATE_PAPER:true}
